#!/bin/sh
set -e

envsubst '${ORIGIN}' < /nginx.conf.template > /etc/nginx/conf.d/default.conf

envsubst '${VALID_REFERERS}' < /valid_referers.conf.template > /etc/nginx/valid_referers.conf

if [ -z "$VALID_REFERERS" ]; then
    echo "# valid_referers 未启用" > /etc/nginx/valid_referers.conf
fi

envsubst '${SECURE_LINK_SECRET}' < /secure_link.conf.template > /etc/nginx/secure_link.conf

if [ -z "$SECURE_LINK_SECRET" ]; then
    echo "# secure_link 未启用" > /etc/nginx/secure_link.conf
fi

# 默认允许所有 IP（无环境变量时）
ALLOWED_IPS=${ALLOWED_IPS:-"0.0.0.0/0"}

# 生成 IP 访问规则
echo "# Generated by entrypoint.sh" > /etc/nginx/conf.d/ip-access-rules.conf
for ip in $ALLOWED_IPS; do
    echo "allow $ip;" >> /etc/nginx/conf.d/ip-access-rules.conf
done
echo "deny all;" >> /etc/nginx/conf.d/ip-access-rules.conf  # 默认拒绝其他 IP

exec "$@"
